### ISSUE TITLE
[Debian] Linker regression

### ISSUE THREAD

**Issue by fervi** [Fluorohydride/ygopro-core#157]
After the last fix that fixes one error, the code compilation has been successful, but the linker has some problems.

Log:
http://meshnet-users.tk/paste/p/hosd/q.txt

**Comment by mercury233** [comment]
did you update you lua to 5.3 correctly?

**Comment by fervi** [comment]
Ok, Debian's bug 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863036

Thanks :)
