### ISSUE TITLE
EVENT_LEAVE_FIELD effects losing their relations

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#166]
As the title said, there's an issue with EVENT_LEAVE_FIELD, after this effect is called, all the relations with other effects with its handler are resetted, but including also that triggered effect itself, this causes issues with cards that negates an effet and then do something with its handler, like Invoked Mechaba, and since the `re:GetHandler():IsRelateToEffect(re)` returns false, in the case of mechaba, the mosnter is not banished.

[here](https://github.com/Fluorohydride/ygopro-core/blob/master/operations.cpp#L3916) here the event is processed, and [here](https://github.com/Fluorohydride/ygopro-core/blob/master/operations.cpp#L3952) all the relations are deleted

**Comment by purerosefallen** [comment]
any solution to that?

**Comment by DailyShana** [comment]
3bb24b931befaf2eb31a5d240a1edc5f5e3c4b73
