### ISSUE TITLE
Bugged chain triggering

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#197]
Under some circumstrances, when forced effects triggers, the core will simply remain stuck, in the archive there's a video that shows this happening. The field is set in this way: Both players control 1 King Tiger Wanghu each, and they have 2 dandylion each in their hands, p1 use hand destruction, and after it resolves, the 4 dandylions trigger summoning 8 tokens, then the King Tigers try to resolve, the p1's correctly triggers 4 times, while the p2's make teh game get stuck after triggering 1 time.
[2018-11-13 19-50-52.zip](https://github.com/Fluorohydride/ygopro-core/files/2591738/2018-11-13.19-50-52.zip)

**Comment by DailyShana** [comment]
Fixed in 4e454aa
