### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by Portalcake** [Fluorohydride/ygopro-core#213]
I'm following the steps on Wiki, but I can't compile Ocgcore.
Build log: https://pastebin.com/QJL3sipM

I don't know what to do now, can you help me?
I'm running a VM with Windows 7 & Visual Studio 2010.

**Comment by edo9300** [comment]
You need at least vs15 to compile the api

**Comment by Portalcake** [comment]
> You need at least vs15 to compile the api

Okay, I'll try it, thanks.

**Comment by Portalcake** [comment]
Now I'm getting:

1>------ Build started: Project: ocgcore, Configuration: Release Win32 ------
1>   Creating library ..\bin\release\ocgcore.lib and object ..\bin\release\ocgcore.exp
1>LINK : fatal error LNK1104: cannot open file '..\bin\release\ocgcore.lib'
1>Done building project "ocgcore.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Running Visual Studio 2019 on Windows 10 (main PC).

**Comment by edo9300** [comment]
To use this repo's premake script correctly, you'll have to create the solution for the entire project (ygopro) and then build the core from there

**Comment by Portalcake** [comment]
Okay, I understand and I've successfully compiled the ocgcore.
But now I'm getting the following errors when I try to compile the ygopro.exe: 

[game.cpp :: line 937]
E0144	a value of type "const irr::c8 *" cannot be used to initialize an entity of type "const wchar_t *"
C2440	'initializing': cannot convert from 'const T *' to 'const wchar_t *'

[menu_handler.cpp :: line 297]
C2664	'BOOL CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION)': cannot convert argument 9 from 'STARTUPINFO *' to 'LPSTARTUPINFOW'

Is there something that I'm doing wrong?

**Comment by edo9300** [comment]
Idk, I work on a different branch that now is a lot different from this one, and that part isn't present in mine

**Comment by edo9300** [comment]
But it seems like an Unicode strings issue, is the project set with Unicode as its character set?

**Comment by Portalcake** [comment]
> But it seems like an Unicode strings issue, is the project set with Unicode as its character set?

According to the Visual Studio, it is set to: Use Multi-Byte Character Set.

**Comment by edo9300** [comment]
Then try switching that to Unicode (even if the premake script should have already done it)
