### ISSUE TITLE
Change to a GPL licence

### ISSUE THREAD

**Issue by kevinlul** [Fluorohydride/ygopro-core#220]
Options:
- GPLv2 to match the main project
- GPLv3 to stay with the latest GPL. GPLv2 has a provision to relicense to later GPL versions easily.
- AGPLv3 to also cover network/server use cases

See also: edo9300/ygopro-core#43

**Comment by purerosefallen** [comment]
Why?

**Comment by kevinlul** [comment]
For consistency with the main project and to preserve the copyleft nature of YGOPro even if only the core is used.

**Comment by purerosefallen** [comment]
But changing the license won't affect the previous versions.

**Comment by kevinlul** [comment]
It'll protect future versions from now forward!

**Comment by purerosefallen** [comment]
In addition, I don't think such protecting are needed.
Though there are sayings that Duel Link is also using a fork of ocgcore (this project) as their logic engine, changing license is not proper here.
Also, I think you are too selfish to have asked us to change license.

**Comment by DailyShana** [comment]
I don't agree what @purerosefallen says.

But the license has been decided long ago under consideration, so I think we will not change license.

**Comment by purerosefallen** [comment]
I think it's time now, for Percy's habit.
Please comment on https://github.com/Fluorohydride/ygopro-core/issues/220 for your opinions.
