### ISSUE TITLE
 Super Polymerization vs Continuous Effects

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-core#247]
I am using **Super Polymerization** as example, but this demonstrates that continuous effects might be applying at incorrect times and/or causing actions to become illegal moves in the middle of their resolution/execution:

I control **Yuki-Musume, the Ice Mayakashi** and have 1 **Starving Venom Fusion Drago**n in my Extra Deck. My opponent controls any 1 **DARK monster** and 1 **Destiny Hero  - Plasma** and its effect that negates my monster's effects is applying, negating **Yuki-Musume, the Ice Mayakashi**'s effect.

If i activate **Super Polymerization** what happens at the moment:

1. I select Plasma and the DARK monster to be used as material.
2. They are sent to the Graveyard as Fusion material.
3. Plasma is no longer on the field, so **Yuki-Musume, the Ice Mayakashi**'s effect starts to apply: I cannot summon non-"Mayakashi" monsters from my Extra Deck.
4. The effect of Super Polymerization stops, **Starving Venom Dragon** is not Fusion Summoned, which is incorrect: the Fusion Summon should happen.

**Comment by kevinlul** [comment]
Is this the same type of problem as infinite loops?

**Comment by DailyShana** [comment]
the continuous effect should always applied immediately. The ruling that the fusion summon still be performed conflicts this.

**Comment by NaimSantos** [comment]
I am adding [this ruling](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=14757&keyword=&tag=-1) ( for Acid Trap Hole vs Blackwing - Kris the Crack ) to the discussion because it seems to confirm the hyphotesis that the effects should not apply
