### ISSUE TITLE
remove unnecessary std::round

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro-core#264]
for example
https://github.com/Fluorohydride/ygopro-core/blob/256d78bf23c6a1acb4eb66e3173f8db34a283f79/libeffect.cpp#L270
when update lua from 5.2 to 5.3, lua_tointeger will get 0 if the value is a decimal like 337.5
we need lua_tonumber and convert it to integer type. However, using std::round is over-thinking, it is still inaccurate. Eg. when the attack of some monster will increase 337.5, according to the rule, the increasement is actually 338, but if decrease 337.5, acturally decrease 337.
So the correctness of treating decimals should be done in script and std::round in core is unnecessary.

**Comment by edo9300** [comment]
Where's this from? From what I know values should always be rounded up, for example, when losing half lp, if your lp are 1, halved is 0.5, but you'll still end up with 1 lp, and I think this reasoning should be applied to attack and other values that can be affected in similar way. Also the std::round was put to mimic the behaviour of lua 5.2, so it's not real overthinking

**Comment by DailyShana** [comment]
>when losing half lp, if your lp are 1, halved is 0.5, but you'll still end up with 1 lp

so the damage is 0, not round(0.5)=1
