### ISSUE TITLE
update MSG_SELECT_UNSELECT_CARD to MSG_SELECT_CARD_STEP

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro-core#272]
Add a new byte to indicate whether it's a new selection or part of some selection process, so that the client can use this information to make the selection more smoothly. For example, the card list panel do not need flash, to avoid Fluorohydride/ygopro#2249.
Maybe there are other improvement.

**Comment by DyXel** [comment]
@edo9300 and I already discussed this before, we arrived at the conclusion that using a optional hint that is interpreted or ignored by the client would be the best course of action to solve this issue. We also think that regardless of the solution there would be the need to modify all the scripts that use SelectUnselect so the client can properly know when a selection truly ended.
