### ISSUE TITLE
"previous" informations not updated when card is overlayed

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#275]
As title says, when a card is overlayed, the previous informations aren't updated to the values the card had on the field, a side efect of this is effects like add_setcode or add_code not being considered when calling previoussetcard/previouscode on the card as xyz material (they're being updated only on move card).

**Comment by DailyShana** [comment]
According to the rule, Xyz material is something not card but still on field, also becoming Xyz material is not leaving field, it seems odd to consider its previous code on field.
So I think we will not consider this until it is really necessary.
