### ISSUE TITLE
Normal Summon Option Cancel When Miss click, Option Normal Summon Cancel 

### ISSUE THREAD

**Issue by themenlight** [Fluorohydride/ygopro-core#277]
Hello Admin
Hello developer and programmer YGOPRO

The First,Ygopro Percy it's Very Good but Some the Duel have prolem

I did Normal monster Be miss (My mouse mis click) ( or I want Normal monster Other on my hand, But I Cant do that , Ygopro haven't Options to CANCEL normal summon that monster.

The Second, Ygopro HAVE OPTION CANCEL Special Summon Monster In Extra deck ( Can Summon or Not Summon When Play If Player Want or NOT want)

But OPTION CANCEL NORMAL MONSTER not have (In The Duel,  I did miss click (mouse) to Monster . But i not want Normal that monster, while i have some monster other on my hand  ( a have more choice) to NORMAL MONSTER. But i cant CANCEL that Monster be MISS .

So i want developer and programmer YGOPRO can Update add Option or Feature  can ( CANCEL NORMAL MONSTER WHEN MISS CLICK) 
The third, Thanks for reading and can fix that prolem please!  

Thanks ADMIN, Developer!

**Comment by DailyShana** [comment]
This is not a place to report prolem of Ygopro Percy

**Comment by themenlight** [comment]
Can you give me code fixed Please??
