### ISSUE TITLE
Number 41 vs Metaltron XII or Master Peace

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-core#284]
If you use an effect to perform the Tribute Summon of either **Master Peace, the True Dracoslaying King** or **Metaltron XII, the True Dracombatant** (similar cards include Horus The Black Flame Dragon LV6) while the effects of **Number 41: Bagooska the Terribly Tired Tapir** ( or similar cards like **Level Limit - Area B**) by using an effect such as those of **Disciples of the True Dracophoenix**, (or True King's Return, or Arrivalrivals)  those monsters are still changed to Defense Position, even when they are unaffected by the respective card types' effects.

This does not happen if you Tribute Summon these cards by the regular procedure, without using an effect.

**Comment by Lyris12** [comment]
Here is a fix for this: add `tc:SetStatus(STATUS_EFFECT_ENABLED,true)` as a new light right after `Duel.Summon` in the script.
