### ISSUE TITLE
Last will like effects not triggering events

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#293]
If you use last will continuous effect to summon an armageddon knight from your deck, you won't be able to use its effect, while if it's summoned directly during the activation, it will.
Sample puzzle
```lua

Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,4)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(28985331,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(28985331,0,0,LOCATION_DECK,1,POS_FACEDOWN)
Debug.AddCard(28985331,0,0,LOCATION_DECK,1,POS_FACEDOWN)

Debug.AddCard(53129443,0,0,LOCATION_HAND,1,POS_FACEDOWN)
Debug.AddCard(85602018,0,0,LOCATION_HAND,1,POS_FACEDOWN)

Debug.ReloadFieldEnd()
```

**Comment by DailyShana** [comment]
it lacks a process point event after solving continuous.
see how to treat it properly in process_phase_event:
https://github.com/Fluorohydride/ygopro-core/blob/332aea238ad1a255406e56e0cebc1cf2b5353b44/processor.cpp#L1201-L1221
