### ISSUE TITLE
Card.GetAttackableTarget not working after entering damage step

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#309]
Currently, if Card.GetAttackableTarget is used on an attacking monster, if no other conditions granting extra attacks are being applied, the returned group will be empty. This behaviour change makes https://github.com/Fluorohydride/ygopro-scripts/blob/master/c8687195.lua no longer work, as
```
local at=Duel.GetAttacker():GetAttackableTarget()
```
will be empty when called, thus returning no valid targets for its effect.

**Comment by DailyShana** [comment]
maybe we should split attack count check from `get_attack_target`

**Comment by DailyShana** [comment]
The effect of 幻影の妖精/Dreamsprite is a forcing damage calculation effect, not a changing attack target effect. It should be the same as No.38, checking available attack target is unnecessary.
>Ｑ：このカードの効果で攻撃対象に選択する事ができない地縛神等を選択してダメージ計算を行う事ができますか？
Ａ：はい、できます。(11/10/28)
https://yugioh-wiki.net/index.php?%A1%D4%B8%B8%B1%C6%A4%CE%CD%C5%C0%BA%A1%D5#faq

it can select _Earthbound Immortal_ monsters

**Comment by DailyShana** [comment]
the script is fixed in Fluorohydride/ygopro-scripts@a6eb21f

`Card.GetAttackableTarget` works well normally during `EVENT_ATTACK_ANNOUNCE` and `EVENT_BE_BATTLE_TARGET`, and no effect need this in damage step.
So I close this for now
