### ISSUE TITLE
It's no longer possible to spsummon/summon rule outside a chain

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#312]
As the title says, with the change made to summon procedures in effects (https://github.com/Fluorohydride/ygopro-core/commit/d5aace84f9e4b3a8cbb3b3b68b071198881eac5d), it's no longer possible to use those function from a continuous effect, or anything that isn't related to a chain, because after the subunit is moved to the reserved variable, it's never restored back.

**Comment by LordOfNightmares** [comment]
yea this doesn't work anymore
```lua
local e3=Effect.GlobalEffect()
e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
e3:SetCode(EVENT_SUMMON_SUCCESS)
e3:SetTargetRange(LOCATION_HAND,0)
e3:SetOperation(function(e,tp,eg)
    local g=Duel.SelectMatchingCard(tp,Filter,tp,LOCATION_HAND,0,0,1,nil)
    local tc=g:GetFirst()
    if tc then Duel.Summon(tp,tc,true,nil) end
end)
Duel.RegisterEffect(e3,tp)
```
```lua
function Filter(c)
    return c:IsSummonable(true,nil)
end
```

**Comment by DailyShana** [comment]
addinig a condition `if(pduel->game_field->core.current_chain.size())` for moving to subunits may fix this.
but I'm a little doubt that `EVENT_SUMMON`/`EVENT_SPSUMMON`(activating _Solemn Warning_) during continuous chain may cause some problem
