### ISSUE TITLE
Incorrect string displayed for MSG_CHAINED

### ISSUE THREAD

**Issue by sleeser** [Fluorohydride/ygopro-core#314]
```
case MSG_CHAINED: {
        int ct = BufferIO::ReadInt8(pbuf);
        if(mainGame->dInfo.isReplay && mainGame->dInfo.isReplaySkiping)
            return true;
        myswprintf(event_string, dataManager.GetSysString(1609), dataManager.GetName(mainGame->dField.current_chain.code));
        mainGame->gMutex.lock();
        mainGame->dField.chains.push_back(mainGame->dField.current_chain);
        mainGame->gMutex.unlock();
        if (ct > 1)
            mainGame->WaitFrameSignal(20);
        mainGame->dField.last_chain = true;
        return true;
    }

```
When a card is activated in a chain, ocgcore will send MSG_CHAINED, which will display the 1609 string which sends "[%ls]is activated". However, in some cases, the card is not "activated", but can be "destroyed" or "banished". We do have MSG_SUMMONING which sends string id 1603 for Normal Summon; MSG_SPSUMMONING which sends string id 1605 for Special Summon; and MSG_FLIPSUMMONING which sends string id 1607 for Flip Summon. There is no messages for for "Destroy" or "Banish". This leads to MSG_CHAINED being used in inappropriate times for the other cases when it's not "activated". We can either create these cases in the MSG_CHAINED code block OR create separate messages for each of these cases.

An example,
1. Striker Dragon is Special Summoned. Rokket Recharger is in the Player's hand.
2. Striker Dragon is destroyed and sent to the Graveyard.
3. Rokket Recharger's effect is triggered from the hand.
4. A message prompt will appear in ygopro which will show "[Striker Dragon] is activated. Chain a card?".

![image](https://user-images.githubusercontent.com/44324682/83566940-7138a000-a529-11ea-9664-8fab346b0bf5.png)

Striker dragon wasn't "activated" but "destroyed", so it is incorrect. This leads to the player getting the wrong message in the game, which can ultimately lead to making the wrong decision.

I propose we add these two strings and two new messages:
!system 1625 [%ls]is destroyed
!system 1626 [%ls]is banished
!system 1627 [%ls]is sent to the Graveyard
!system 1628 [%ls]is returned to Hand
!system 1628 [%ls]is returned to Deck

MSG_DESTROYED
MSG_BANISHED
MSG_SENTTOGRAVE
MSG_RETURNTOHAND
MSG_RETURNTODECK

**Comment by sleeser** [comment]
@DailyShana can you review this

**Comment by edo9300** [comment]
This has nothing to do with the core, the wrong string is a leftover in the client, not the core, it should be the client updating the string according to the messages it receives, precisely, the strings you're requesting to be added, should be created by the client when parsing messages like msg_move, from there you'd be able to extrapolate that information. The core cannot know what caused a specific event to trigger an effect.

**Comment by DailyShana** [comment]
Striker Dragon is indeed destroyed by effect of itself, so "[Striker Dragon] is activated" is not wrong.
It's very often that multiple trigger effects activated at the same time with different kind of event(e.g. use Dark Hole to destroy Striker dragon and Elemental HERO Shadow Mist), so it's impossible to give an "accurate string" for specific card.

**Comment by sleeser** [comment]
alright then

**Comment by sleeser** [comment]
@edo9300 Thanks for the suggestion. I think though that even if you were to use msg_move with reason_destroy, that won't address other cases like if the card was sent to the graveyard without being destroyed. There aren't enough of those reasons to address every case. The screenshot I showed above was from edopro as you saw. If you can parse msg_move in your client to show "destroyed", "banished", "returned to hand", or "returned to deck" instead of "activated", then it would be more clear to players.
