### ISSUE TITLE
Incorrect reason set to destroy monsters with "You can only control 1" unclassified effect

### ISSUE THREAD

**Issue by NaimSantos** [Fluorohydride/ygopro-core#328]
You control 2 **Bujin Yamato**, 1 face-up and another face-down. Attacking the one face-down with something like **Draco Berserk of the Tenyi** causes the effect Draco Berserk of the Tenyi to trigger.
Debugging for EVENT_TO_GRAVE and the reason returns `33` -> 0x21 = REASON_DESTROY+REASON_BATTLE, when the monster should be sent to the graveyard by REASON_RULE, as per Damage Step interactions (it should be sent to the graveyard "after damage calculation") and Draco Berserk of the Tenyi would then be unable to trigger.

Setup puzzle:
```
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)
Debug.AddCard(5041348,0,0,LOCATION_MZONE,1,POS_FACEUP_ATTACK)
Debug.AddCard(32339440,1,1,LOCATION_MZONE,2,POS_FACEUP_DEFENSE)
Debug.AddCard(32339440,1,1,LOCATION_MZONE,1,POS_FACEDOWN_DEFENSE)


Debug.ReloadFieldEnd()
aux.BeginPuzzle()
```

**Comment by DailyShana** [comment]
The correct rule is the following:
As the face-down _Bujin Yamato_ has lower def, it is in the status of battle destroy, so its self destroy effect will not apply; thus after damage calculation, the other _Bujin Yamato_ will be self destoyed; finally, the attacked _Bujin Yamato_ will be battle destroyed normally.

**Comment by DailyShana** [comment]
The effect of _Draco Berserker of the Tenyi_ can be activated is just because the attacked _Bujin Yamato_ is battle destroyed, not self destroyed.
The problem is the face-up _Bujin Yamato_ should be self destroyed after damage calculation.

**Comment by DailyShana** [comment]
After confirming, "You can only control 1" is unclassified effect, which still applies in the status of battle destroy, which is different to self destoy under some condition.
