### ISSUE TITLE
WARNING: Impossibility to update to any newer lua version

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#337]
Starting from lua 5.4, the handling of the call stack got changed, this change caused the entire script ecosystem used by ygopro to break, as now the stack for recursive functisn is way lower than before, and the average utility function recursion takes up too much of it, so until someting in the api allows to properly circumvent this limitation (there's a new api function ``lua_setcstacklimit`` that shoudl be used to increase the stack size, but that doesn't seem to change this behaviour (even when set to the max allowed stack size)).

https://lwn.net/Articles/826134/
https://news.ycombinator.com/item?id=23687000
http://lua-users.org/lists/lua-l/2019-06/msg00083.html

**Comment by DailyShana** [comment]
problem fixed?

**Comment by edo9300** [comment]
Yes, fixed long ago, I had just forgot to close this. https://github.com/edo9300/ygopro-core/commit/ab46d67d6d710016bf9ab2f59f1cd96fc4c48021
