### ISSUE TITLE
EFFECT_SPSUMMON_PROC does not check special summon limits after its operation

### ISSUE THREAD

**Issue by wyykak** [Fluorohydride/ygopro-core#354]
For example, Flower Cardian Boardefly has an effect like _your opponent cannot activate effects of cards in the Graveyard, also they cannot Special Summon monsters from the Graveyard_. If a Machina Fortress itself is discarded during the special summon procedure, it will be special summoned from the graveyard, which will **ignore** the special summon limit from Flower Cardian Boardefly.

This is because EFFECT_SPSUMMON_PROC only checks limits like EFFECT_CANNOT_SPECIAL_SUMMON before the procedure starts. This behavior seems to be unexpected since both the description and the actual implementation (GetSummonLocation()) show that the Machina Fortress mentioned above is special summoned from the graveyard, rather than where the procedure initiated, that is, your hand. Therefore, it should obey the limit applied by other effects.

**Comment by edo9300** [comment]
The checks don't have to be done in the core, but in the scripts themselves, in this case it's fortress that has to check, because blocking the summon during the operation would be wrong as well, because that'd be an illegal move in first place

**Comment by wyykak** [comment]
> The checks don't have to be done in the core, but in the scripts themselves, in this case it's fortress that has to check, because blocking the summon during the operation would be wrong as well, because that'd be an illegal move in first place

But I don't think there is a way to check whether a card can be sp summoned from GY while it is in hand. APIs currently provided can only check if a specific card can be summoned (from its current location). Therefore only after the fortress is sent to GY can I find out the fact that it can't be sp summoned there, but the procedure has already initiated.

**Comment by edo9300** [comment]
But that isn't an issue with the effect, it's an issue with the script implementation
