### ISSUE TITLE
关于“场上所有卡状态变化时的必发效果”的处理问题

### ISSUE THREAD

**Issue by luoxueyasha** [Fluorohydride/ygopro-core#387]
目前OCG里还没有这种类型的卡，但是目前EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F得到的结果是“每次满足条件的场合发动”（如：黑色花园），而不是“每次满足条件**时**发动”，效果不会引起错时点。  
因为diy卡有这类需求所以就想问问目前的core能不能实现这部分内容。

**Comment by mercury233** [comment]
规则上必发效果是不会错过时点的
