### ISSUE TITLE
Bye Bye Damage once per turn clause is not respected when two copies are activated in the same chain

### ISSUE THREAD

**Issue by Locorock** [Fluorohydride/ygopro-core#423]
If you activate bye bye damage during damage calc and chain a second copy to it, both are going to resolve and the effect is going to be applied twice, dealing 4 times the damage taken to the opponent. The card clearly states that the effect can only be applied once per turn and an ocg ruling confirms that only one instance of the card's effect should be applied in this situation.

**Comment by salix5** [comment]
Fluorohydride/ygopro-scripts@6c3065aa9270e3ae93c29fbe5a05b32a2bc01995
fixed
Thank you!
