### ISSUE TITLE
OCG vs TCG Rulings

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro-core#43]
`ygopro-core` currently only implements OCG rulings, it was even called `ocgcore` at one point. There is a very loud and constant call from the user base of YGOPro to have TCG rulings implemented and there is now a body of volunteers to help sort out ruling differences.

I am curious what TCG mechanics are currently implemented, how to trigger them, and how we can move forward with the highly requested feature.

If it is not possible to implement TCG rulings; why, and how can we remove this roadblock? If its a matter of switching between TCG and OCG and doubling the work, why not have the TCG ruled cards in a seperate folder and if the `c00000000.lua` file exist use it else use the one in the other file, if TCG mode is enabled.

I am not concerned about server side implementations at this time.

Thank you ahead of time.

**Comment by joshjosh100** [comment]
I believe this issue should be addressed soon.
