### ISSUE TITLE
Implement "Old Replay Rule" as an additional game rule

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-core#44]
We would like to implement Goat Format with ygopro, but one of the essential rules was that replays behaved differently. During 2005, if an attack was cancelled during a replay, the player was able to choose to attack with the same monster later in the same Battle Phase. This was later changed in 2006 to the rules enforced today. In my mind for how this would work, it would be a checkbox like how "Enable Obsolete TCG Rulings" works.

**Comment by joshjosh100** [comment]
I believe ygopro should have a settings on the main menu for TCG rulings, OCG rulings, and generic option such as sound. TCG rulings enabled default on TCG games, and OCG enabled on TCG/OCG or OCG only games. TCG/OCG can have changeable default in this aforementioned setting menu.

**Comment by DailyShana** [comment]
won't implement any old rules before [Master Rules](http://yugioh-wiki.net/index.php?%A5%DE%A5%B9%A5%BF%A1%BC%A5%EB%A1%BC%A5%EB), which ygopro was developed on the base of.
