### ISSUE TITLE
Diviner of the Herald-like effects leak deck order without shuffling

### ISSUE THREAD

**Issue by ReinUsesLisp** [Fluorohydride/ygopro-core#514]
Diviner of the Herald's ① effect can send cards from Deck or Extra Deck. When this effect is activated, ygopro will show all Fairy-type monsters in the Deck and Extra Deck in order. If an Extra Deck monster is chosen, the deck will not be shuffled and the order of all Fairy monsters in deck will be known to the player.

Here is a replay using Convulsion of Nature to show the cards, but it's not needed to reproduce it:
[DivinerRepro.zip](https://github.com/Fluorohydride/ygopro-core/files/13261354/DivinerRepro.zip)

The same may happen with other cards like Stray Purrely Street that summon or attach cards from GY or Deck.

**Comment by Wind2009-Louse** [comment]
https://github.com/Fluorohydride/ygopro-core/pull/564
