### ISSUE TITLE
How to use DUEL_SIMPLE_AI in duel?

### ISSUE THREAD

**Issue by salvadorc17** [Fluorohydride/ygopro-core#53]
How to use this, and make opponent do automatic moves??

**Comment by Zayelion** [comment]
Its set via `duel_options` ie via the gframe on game start. There is currently no way of triggering it in the game code. Does anything beyond prevent the second player from ever saying no. I could be misunderstanding the code.

**Comment by salvadorc17** [comment]
Do you mean that this will force all opponent card activation in responses to my actions/cards?

**Comment by Zayelion** [comment]
No just yes no's. It looks like the start of incomplete AI.

**Comment by salvadorc17** [comment]
What you mean edit one of the game modes, in puzzle there is SIMPLE_ai, that do activate trap cards and quickplay.
