### ISSUE TITLE
Tag Dueling on YGOPro isn't accurate

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-core#57]
The Tag Duel rules on YGOPro are based on the OCG's rules for how to play it, which are listed here: http://www.yugioh-card.com/japan/howto/

However, this is one of the rules listed that contradicts with how Tag Dueling works on YGOPro

> If an effect returns a card from the field, Graveyard, etc. to the hand or Deck, the card is returned to its original owner's hand/Deck.  

Currently, a card returned to the hand/Deck will return to the current player rather than the original owner.  

There's also a rule where a player cannot use his/her partner's face-up Pendulum Monsters from the Extra Deck

> Each player uses his/her own Extra Deck, and cannot refer to or use cards that are in his/her partner's Extra Deck. Therefore, the Pendulum Monsters that have been placed on your partner's Extra Deck cannot be used.

**Comment by shadowfox87** [comment]
This is an issue that was pointed out months ago in early 2016. It's not something they can fix unfortunately. Other things like SEGOC for TCG are fixable, but not this. It requires a complete rewrite of most of the code.

**Comment by TheOnePharaoh** [comment]
wait so the pendulum cards go to my own extra deck (face-up) not my partner's
that's actually a good thing
usually Tag partners don't make use of pendulums if they  and the pendulum player would be able to use those monsters best.
I personally had many occasions where I needed my resources that have gone in my partner's extra.

**Comment by joshjosh100** [comment]
I believe we should do a complete rewrite of the code for it to be more modular, and object oriented. For cases such as this with rushed or overlooked rules.

**Comment by DailyShana** [comment]
the rule about tag duel has been deleted by official and even during the time that link exists, there is no so called offical tag duel rule
