### ISSUE TITLE
new filter for duel option

### ISSUE THREAD

**Issue by lllyasviel** [Fluorohydride/ygopro-core#67]
how about different 'ot' like 1 for ocg, 2 for tcg, 3 for tcg/ocg, 4 for anime, 8 for illegal, 16 for video game exclusive, and 32 for custom?

**Comment by Zayelion** [comment]
OT is handled by the UI. This repository is for the script processor. It can be compiled separately and has application in other products.  

Also if you have a variant please link it here : https://github.com/Fluorohydride/ygopro/issues/1628
