### ISSUE TITLE
can please you add EVENT_DECK_SHUFFLE back

### ISSUE THREAD

**Issue by AndreOliveiraMendes** [Fluorohydride/ygopro-core#68]
im sure it will be usefull EVENT, can you add it?
there a implemented mode on ygopro percy that actually need this effect, actually can't hardcode it cause not simply like "when this card effect shuffle a deck" but at "when the deck is shuffled" indepedent of what card shuffled it.

**Comment by DailyShana** [comment]
not such event in the rule
