### ISSUE TITLE
Duel.ChangeAttacker() doesn't work anymore

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro-core#71]
As it's written in the title, the funciton ChangeAttacker() doesn't work anymore, i think this is caused by the removing of sub_attacker in this commit: https://github.com/Fluorohydride/ygopro-core/commit/8804e8c6ebceaaf450ba3aa12b01911f309d71be#diff-4d3e75d312bd06042b71854fa0c82846
Because after this change, the game doesn't check properly the new attacker, so the attack is canceled

**Comment by salix5** [comment]
Investigating

**Comment by shadowfox87** [comment]
@salix5 Hi, just reminding you regarding this. Please look at it.
