### ISSUE TITLE
a solution for TCG

### ISSUE THREAD

**Issue by lllyasviel** [Fluorohydride/ygopro-core#75]
简单的说就是脚本里面加一个EFFECT_TYPE_TRIGGER_F/EFFECT_TYPE_TRIGGER_O来辨认这张卡要不要自动排序连锁。TCG/OCG主要这一个区别。而且实现起来很方便。
我觉得如果OCGcore需要实现TCG的话，最快最方便的解决方案就是这个。
如果允许合并到ocgcore的话，这个方案是改动最小的。
AntiMetaman的原文如下：
The major difference between tcg and ocg is SEGOC. This is the "Auto Chain Order" function in ygopro. When a duel uses the ocg banlist, Auto Chain Order should always be OFF.
When the duel uses the tcg banlist, Auto Chain Order should be ON for mandatory trigger effects but it should be OFF for optional trigger effects.
The way to distinguish between mandatory and optional is EFFECT_TYPE_TRIGGER_F is forced (non-optional)
EFFECT_TYPE_TRIGGER_O is optional
This will be in the script.
Hence, you can write an if statement to chain when Auto Chain Order should be off and on for tcg. Then it is very accurate.

**Comment by Zayelion** [comment]
This would require a new API command to pass in the TCG mode flag. Banlist are currently handled by the shell (ygopro/gframe, ygocore, ygosharp, etc.) That is to say the banlist is superficial to `ygopro-core`. It should be noted that all server software that directly interacts with `ygopro-core` is in active development so is not a reason to not change the API.
